config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'
  get '/auth/twitter', as: :login

  get '/auth/twitter/callback', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'
  get '/timeline', :to => "tweets#timeline"
  get '/my_tweets', :to => "tweets#index"
  resources :tweets, only: [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.image              = auth_info.info.image
      new_user.oauth_token        = auth_info.credentials.access_token
      new_user.oauth_token_secret = auth_info.credentials.access_token_secret
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #render text: request.env["omniauth.auth"].inspect
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to timeline_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @screen_name = current_user.screen_name
    @tweets = service.tweets
  end

  def timeline
    @timeline = service.timeline
    @followers = service.followers
  end

  def new
  end

  def create
    @new_tweet = service.compose_tweet(twitter_params[:message])
    #redirect_to tweets_path
  end


private
  def service
    @service ||= TwitterService.new(current_user)
  end

  def twitter_params
    params.require(:tweet).permit(:message)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twittertoo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_compose_tweet.html.erb
<button><%= link_to "Compose Tweet", new_tweet_path %></button>

app/views/tweets/_logout.html.erb
<button><%= link_to "logout", logout_path %></button>

app/views/tweets/_navbar.html.erb
<%= link_to "Back to Timeline", timeline_path %><br>
<%= link_to "List of Your Tweets", my_tweets_path %><br>

app/views/tweets/_profile.html.erb
Screen Name: <%=  current_user.screen_name %><br>
Name: <%=   current_user.name %><br>
Followers: <%=  @followers.count %>

app/views/tweets/create.html.erb
<h3>Success!</h3>
<p>Your tweet has been sent!</p>
<%= link_to "Would you like to send another?", new_tweet_path %><br>
<%= render "navbar" %>
<%= render "logout" %>

app/views/tweets/index.html.erb
<h1>Your Tweets</h1>

<% @tweets.each do |tweet| %>
<%= tweet.text %><br>
<% end %>
<br>
<%= render "navbar" %><br>
<%= render "logout" %>

app/views/tweets/new.html.erb
<p>
  <%= form_for :tweet, url: tweets_path, method: :post do |f| %>
    <%= f.label "Type Tweet Here" %>
    <%= f.text_field :message %>
    <%= f.submit "Send Tweet" %>
  <% end %>
</p>
<br>
<%= render "navbar" %>
<br>
<%= render "logout" %>

app/views/tweets/timeline.html.erb
<%= render "profile" %><br>
<%= render "compose_tweet" %>

<h4 class="center-align"><%=current_user.screen_name%>: Here Are The Tweets From The Folks You Follow</h4>
<% @timeline.each do |status|%>
<div class="row">
   <div class="col s12">
     <div class="card-panel teal">
       <span class="white-text"><%= status.text %><br></span>
     </div>
   </div>
 </div>

<% end %>

<%= render "logout" %><br>
<%= render "navbar" %>

app/views/welcome/index.html.erb
<% if current_user %>
  <p>hello, <%= current_user.name %></p>
  <%= link_to "logout", logout_path %><br>
  <%= link_to "All Of My Tweets", my_tweets_path %><br>
  <%= link_to "My Timeline", timeline_path %><br>
<% else %>
  <%= link_to "login", login_path %>
<% end %>